set -sg escape-time 5


# Change the prefix key
unbind C-b
set -g prefix F12
bind F12 last-window 

# Binding for pane splitting
bind -n F6 choose-tree -sZ

bind -n F7 previous-window
bind -n F8 next-window

bind -n F9 copy-mode -u
bind -T copy-mode F9 send-keys -X cancel
bind -T copy-mode-vi F9 send-keys -X cancel

bind F10 split-window -v
bind -n F10 select-pane -t :.+
bind F11 split-window -h
bind -n F11 select-pane -t :.-

unbind '"'
unbind %

# Fix incorrect terminal colors
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Enable vi-bindings for copy mode
setw -g mode-keys vi

# Setup vi-style copy/paste
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# Vi-style navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Larger stack trace
set -g history-limit 50000

# remove the date and time from the status line
set -g status-right ""

