#!/bin/sh

# 1. Hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16

# MATE Integration Rules
bspc rule -a Mate-panel manage=off
bspc rule -a mate-panel manage=off
bspc rule -a Mate-polkit state=floating
bspc rule -a Mate-volume-control state=floating
bspc rule -a Mate-calc state=floating

# Optional sensible defaults
bspc config top_padding        32
bspc config border_width       2
bspc config window_gap         0
bspc config split_ratio        0.50

bspc config focused_border_color "#e82b8b"
bspc config normal_border_color  "#888888"

# Fix mouse
xsetroot -cursor_name left_ptr

